### ISSUE TITLE
Fix Reflector

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/reflector-cluster#41]
### done

- [x] [5] write iterativefindnode, iterativefindvalue
- [x] [3] write transaction manager to handle responses
- [x] [5] test communication with real daemon. there are probably still inconsistencies in rpc calls
- [x] [3] what is `token` for? do we need token manager?
- [x] [3] RPC interface to print debugging info and make changes while node is running
- [x] [5] test on live dht
- [x] [3] rearrange code for readability and external use
- [x] [5] write bootstrap node
- [x] [5] use tree for k-buckets in routing table (including bucket splitting)
- [ ] [3] ~~implement caching (storing findValue results at closest node that did not return a value)~~

### v1 (just mirroring)

- [x] [1] drop `last_announced_at` on live db (db needs restart before this)
- [x] [3] upload all existing blobs/streams
- [x] [2] investigate why db connections keep getting stuck (maybe kill them after X time?)
- [x] [3] use for ytsync on full blast for little while to test everything
- [x] [5] switch out old reflector for new reflector, then reupload old reflector blobs
- [x] [15] babysit new reflector while improving monitoring/robustness

### v2 (with dht)

- [x] [5] rate limiting for hash announcer (make sure we dont announce too fast, alert when we cannot announce everything in an hour)
- [ ] [1] slack us when we can't announce everything
- [ ] [3] implement bucket grooming
- [ ] [2] make sure nodes are being correctly updated/dropped when they respond or fail to respond
- [ ] [2] persist data and nodeID to disk on shutdown, load it on startup
- [ ] [?] get the integration tests from python to pass

### later

- [ ] [5] peers in routing table and in peer store should be pointers to single contacts, so that only one instance of any given contact exists at a time.
- [ ] [3] implement key republishing
- [ ] [2] remove all panics, handle all errors
- [ ] [2] send error responses (do we even need these? just don't respond)
- [ ] [2] smooth out announces so they don't bunch around the reannounce time

### risks

- dht implementation correctness
- ~~performance on downloading blobs from s3 and serving them~~
- caching and hard disk issues around downloading blobs
- ~~redistributing announce load when nodes join/leave the cluster~~
- ~~speed to upload blobs to s3~~

### links

http://xlattice.sourceforge.net/components/protocol/kademlia/specs.html
http://www.maymounkov.org/papers/maymounkov-kademlia-lncs.pdf
http://blog.notdot.net/2009/11/Implementing-a-DHT-in-Go-part-2
http://www.scs.stanford.edu/17au-cs244b/labs/projects/kaplan-nelson_ma_rachleff.pdf
http://www.bittorrent.org/beps/bep_0005.html
https://blog.libtorrent.org/2016/09/dht-bootstrap-node

**Comment by lyoshenka** [comment]
iterativeFind description:

target = hash that you're looking for
activeNodes = [], always sorted by distance to target
toContact = [], always sorted by distance to target
contacted = {}

start!

put all nodes in routing table into the toContact list
run ALPHA workers
each worker will asynchronously:
  - contact first node in toContact list
  - if node does not reply in some time, drop it and move on to next node
  - if node replies, insert it into activeNodes
  
  - if node replies with the value for FindValue call, return that value and immediately end the whole process
  - if node replies with contacts, insert the contacts that have not been contacted yet into toContact
  
  - if len(toContact) == 0 or len(activeNodes) >= K and activeNodes[K-1] is closer to target than toContact[0], quit

if FindValue found a value, return it. otherwise return first K activeNodes

**Comment by lyoshenka** [comment]
Update: tested downloading blobs from s3 and serving them. It took about 1 minute to download a stream of 46 blobs (including sd blob). Reflector and lbrynet were both running locally, so I think basically all the time was spent downloading blobs from s3. So that comes to a bit less than 1 second per blob. I expect that running inside AWS will make the download even faster, and we can do caching for common blobs. Therefore, I'm no longer worried about S3 being slow in this design.
